#!/bin/bash
echo "🔍 DIAGNOSTIC COMPLET DE L'ACCÈS GITHUB"
echo "======================================"
echo ""

echo "📋 ÉTAPE 1 : Vérification des tokens"
echo "-----------------------------------"
echo "1. Allez sur : https://github.com/settings/tokens"
echo "2. Vérifiez si vos tokens sont toujours valides"
echo "3. Regardez les dates d'expiration"
echo ""

echo "🔒 ÉTAPE 2 : Vérification des permissions repository"
echo "--------------------------------------------------"
echo "1. Allez sur : https://github.com/Jboner-Corvus/AgenticForge/settings/collaborators"
echo "2. Vérifiez que votre compte est toujours collaborateur"
echo "3. Vérifiez vos permissions (Write/Admin)"
echo ""

echo "🛡️  ÉTAPE 3 : Vérification des branch protection rules"
echo "-----------------------------------------------------"
echo "1. Allez sur : https://github.com/Jboner-Corvus/AgenticForge/settings/branches"
echo "2. Vérifiez si de nouvelles règles ont été ajoutées"
echo "3. Vérifiez la branche 'main' spécifiquement"
echo ""

echo "⚙️  ÉTAPE 4 : Vérification des paramètres de sécurité"
echo "--------------------------------------------------"
echo "1. Allez sur : https://github.com/settings/security"
echo "2. Vérifiez si 2FA est toujours configuré correctement"
echo "3. Vérifiez les authorized applications"
echo ""

echo "🔄 QUESTIONS DE DIAGNOSTIC :"
echo "=========================="
echo ""
echo "❓ Avez-vous récemment :"
echo "   - Changé votre mot de passe GitHub ?"
echo "   - Activé/désactivé l'authentification 2FA ?"
echo "   - Modifié les paramètres de sécurité de votre compte ?"
echo "   - Eu des problèmes de connexion à GitHub ?"
echo ""
echo "❓ Le propriétaire du repository a-t-il :"
echo "   - Modifié les paramètres du repository ?"
echo "   - Ajouté des règles de protection de branche ?"
echo "   - Changé les permissions des collaborateurs ?"
echo ""
echo "Tapez 'o' pour OUI à l'une de ces questions, 'n' pour NON :"
read reponse

if [ "$reponse" = "o" ]; then
    echo "🎯 Problème identifié !"
    echo "Le changement soudain suggère une modification récente des paramètres."
    echo ""
    echo "💡 SOLUTION :"
    echo "1. Vérifiez d'abord vos tokens GitHub"
    echo "2. Si nécessaire, générez un nouveau token avec TOUS les scopes"
    echo "3. Vérifiez les paramètres du repository"
    echo ""
    echo "Nouveau token recommandé avec scopes : repo, workflow, delete_repo"
else
    echo "🔍 Problème plus subtil..."
    echo "Essayons une approche différente."
    echo ""
    echo "💡 SOLUTION ALTERNATIVE :"
    echo "1. Essayez de cloner le repository dans un nouveau dossier"
    echo "2. Comparez la configuration Git"
    echo "3. Vérifiez s'il y a des différences dans les credentials"
fi