

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./packages/ui/dist:/usr/share/nginx/html:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Fait en sorte que Redis démarre avant Nginx
    depends_on:
      - redis

  redis:
    # Utilise l'image officielle et légère de Redis
    image: redis:alpine
    ports:
      # Lie le port Redis de votre machine à celui du conteneur.
      # Ainsi, votre backend local peut toujours s'y connecter sur localhost:6379
      - "6379:6379"
    volumes:
      # Ce volume permet de sauvegarder les données de Redis sur votre machine
      # pour ne pas les perdre quand le conteneur s'arrête.
      - ./redis-data:/data