steps:
  # Build the core service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/agentic-forge-core:$COMMIT_SHA', '-f', 'packages/core/Dockerfile', '.']
  
  # Build the UI service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/agentic-forge-ui:$COMMIT_SHA', '-f', 'packages/ui/Dockerfile.web', '.']
    
  # Push the core service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agentic-forge-core:$COMMIT_SHA']
    
  # Push the UI service image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agentic-forge-ui:$COMMIT_SHA']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'agentic-forge-core'
      - '--image'
      - 'gcr.io/$PROJECT_ID/agentic-forge-core:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'agentic-forge-ui'
      - '--image'
      - 'gcr.io/$PROJECT_ID/agentic-forge-ui:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/agentic-forge-core:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/agentic-forge-ui:$COMMIT_SHA'
