services:
  redis:
    image: redis:7.2-alpine
    container_name: agentic_forge_redis
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 6379 ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - agentic_network

  postgres:
    image: postgres:16-alpine
    container_name: agentic_forge_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-agenticforge}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - agentic_network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_forge_server
    ports:
      - "${PUBLIC_PORT:-8080}:3001"
    volumes:
      - ./workspace:/usr/src/app/workspace
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment: &common_env
      - NODE_ENV=production
      - DOCKER=true
      - HOST=0.0.0.0
      - PUBLIC_PORT=${PUBLIC_PORT}
      - PORT=${PORT:-3001}
      - LOG_LEVEL=${LOG_LEVEL}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEB_PORT=${WEB_PORT}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - GEMINI_API_KEY=${LLM_API_KEY}
      - SESSION_PORT=${SESSION_PORT}
      - HOST_PROJECT_PATH=${HOST_PROJECT_PATH}
      - TOOLS_PATH=/usr/src/app/packages/core/dist/tools
    mem_limit: ${CONTAINER_MEMORY_LIMIT:-2g}
    restart: unless-stopped
    env_file: ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s
    networks:
      - agentic_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_forge_worker
    command: node packages/core/dist/worker.js
    depends_on:
      redis:
        condition: service_healthy
    environment: *common_env
    mem_limit: ${CONTAINER_MEMORY_LIMIT:-2g}
    restart: unless-stopped
    env_file: ./.env
    networks:
      - agentic_network

  web:
    build:
      context: .
      dockerfile: packages/ui/Dockerfile.web.nginx
    container_name: agentic_forge_web
    ports:
      - "${WEB_PORT:-3002}:3000"
    depends_on:
      server:
        condition: service_healthy
    environment: *common_env
    mem_limit: ${CONTAINER_MEMORY_LIMIT:-2g}
    restart: unless-stopped
    env_file: ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - agentic_network

  

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "13133:13133" # Health Check extension
      - "8888:8888" # Prometheus metrics
    depends_on:
      - redis
    networks:
      - agentic_network
    

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  agentic_network:
    driver: bridge
    name: agentic_forge_network
