import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts', 
    'src/webServer.ts', 
    'src/worker.ts', 
    'src/server-start.ts',
    'src/modules/tools/definitions/**/*.ts'
  ],
  format: ['esm'],
  dts: true,
  clean: true,
  external: [
    'express',
    'cookie-parser',
    'dockerode',
    'jsonwebtoken',
    'pg',
    'ioredis',
    'playwright',
    'puppeteer',
    'zod',
    'bullmq',
    'chokidar',
    'dotenv',
    'fastmcp',
    'jsdom',
    'uuid',
    'vitest-mock-extended',
    '@opentelemetry/api',
    '@opentelemetry/auto-instrumentations-node',
    '@opentelemetry/exporter-metrics-otlp-grpc',
    '@opentelemetry/exporter-trace-otlp-grpc',
    '@opentelemetry/resources',
    '@opentelemetry/sdk-metrics',
    '@opentelemetry/sdk-node',
    '@opentelemetry/semantic-conventions',
    'pino',
    'cookie-signature',
    // Node.js built-in modules
    'crypto',
    'path',
    'fs',
    'os',
    'util',
    'stream',
    'http',
    'https',
    'url',
    'events',
    'buffer',
    'net',
    'tls',
    'zlib',
    'querystring',
    'assert',
    'child_process',
    'constants',
    'dns',
    'domain',
    'module',
    'perf_hooks',
    'process',
    'punycode',
    'readline',
    'repl',
    'string_decoder',
    'sys',
    'timers',
    'tty',
    'v8',
    'vm',
    'worker_threads',
    'wasi',
    'async_hooks',
    'cluster',
    'dgram',
    'diagnostics_channel',
    'inspector',
    'trace_events',
    'v8/tools/prof_process',
    'v8/tools/tick-processor',
    'node:crypto',
    'node:path',
    'node:fs',
    'node:os',
    'node:util',
    'node:stream',
    'node:http',
    'node:https',
    'node:url',
    'node:events',
    'node:buffer',
    'node:net',
    'node:tls',
    'node:zlib',
    'node:querystring',
    'node:assert',
    'node:child_process',
    'node:constants',
    'node:dns',
    'node:domain',
    'node:module',
    'node:perf_hooks',
    'node:process',
    'node:punycode',
    'node:readline',
    'node:repl',
    'node:string_decoder',
    'node:sys',
    'node:timers',
    'node:tty',
    'node:v8',
    'node:vm',
    'node:worker_threads',
    'node:wasi',
    'node:async_hooks',
    'node:cluster',
    'node:dgram',
    'node:diagnostics_channel',
    'node:inspector',
    'node:trace_events'
  ],
  noExternal: [],
  target: 'es2022',
  shims: true,
  assets: [{
    from: ['./src/modules/agent/system.prompt.md'],
    to: ['./dist/system.prompt.md']
  }],
});
