export const en = {
  agentReady: "🎯 **Agent ready.** Please enter your *Auth Token* to begin.",
  newSessionCreated: "🔄 **New Session Created.**",
  newSessionGenerated: "New session ID generated",
  sessionRetrieved: "Session ID retrieved",
  checkingServerHealth: "Checking server health...",
  serverStatus: "Server Status",
  serverOnline: "Online",
  serverOffline: "Offline",
  serverHealthCheckFailed: "Server health check failed",
  tokenLoadedFromEnv: "Token loaded from environment (VITE_AUTH_TOKEN)",
  tokenLoadedFromCookie: "Token loaded from cookie",
  tokenLoadedFromLocalStorage: "Token loaded from localStorage",
  noTokenFound: "No token found",
  interfaceInitialized: "Interface initialized (useEffect)",
  tokenSaved: "Your authentication token has been saved.",
  newTokenSaved: "New token saved",
  tokenRemoved: "Your authentication token has been removed.",
  tokenDeleted: "Token deleted",
  historyCleared: "The local history has been cleared.",
  debugLogCleared: "Debug log cleared.",
  sessionActive: "Session Active",
  sessionError: "Session Error",
  sessionUnknown: "Session Unknown",
  tokenValid: "Token Valid",
  tokenRequired: "Token required",
  settings: "Settings",
  notifications: "Notifications",
  authToken: "Auth Token:",
  authTokenPlaceholder: "Paste your Bearer Token here",
  saveToken: "Save Token",
  agentThinking: "🤔 Agent thinking...",
  
  tokenRequiredInput: "🔑 Please save a Bearer Token...",
  describeYourGoal: "💬 Describe your goal...",
  interrupt: "Interrupt",
  sendMessage: "Send Message",
  controlPanel: "Control Panel",
  agentStatus: "Agent Status",
  sessionId: "Session ID",
  toolsDetected: "Tools Detected",
  connectionStatus: "Connection Status",
  online: "✅ Online",
  offline: "❌ Offline",
  agentCapabilities: "Agent Capabilities",
  sessionManagement: "Session Management",
  saveCurrentSession: "Save Current Session",
  noSessionsSaved: "No sessions saved yet.",
  active: "Active",
  toolCreation: "Tool Creation",
  codeExecution: "Code Execution",
  shellAccess: "Shell Access",
  browserAccess: "Browser Access",
  sandboxAccess: "Sandbox Access",
  quickActions: "Quick Actions",
  newSession: "🔄 New Session",
  clearHistory: "🗑️ Clear History",
  debugLog: "Debug Log",
  frontend: "Frontend",
  clear: "Clear",
  hide: "Hide",
  show: "Show",
  toolUsed: "🛠️ Tool used:",
  toolExecutedSuccessfully: "Tool executed successfully.",
  llmConfiguration: "LLM Configuration",
  llmProvider: "LLM Provider:",
  selectLlmProvider: "Select an LLM provider",
  llmModel: "LLM Model:",
  selectLlmModel: "Select an LLM model",
  llmApiKey: "LLM API Key:",
  llmApiKeyPlaceholder: "Paste your LLM API key here (optional)",
  saveLlmSettings: "Save LLM Settings",
  llmSettingsSaved: "LLM settings saved.",
  login: "Login",
  email: "Email",
  password: "Password",
  separator: "Separator",
  profile: "Profile",
  typeYourMessage: "Type your message...",
  llmApiKeyManagement: "LLM API Key Management",
  openAiApiKeyInput: "OpenAI API Key Input",
  addOpenAiApiKey: "Add OpenAI API Key",
  grokApiKeyInput: "Grok API Key Input",
  addGrokApiKey: "Add Grok API Key",
  kimika2ApiKeyInput: "Kimika2 API Key Input",
  addKimika2ApiKey: "Add Kimika2 API Key",
  deepseekApiKeyInput: "Deepseek API Key Input",
  addDeepseekApiKey: "Add Deepseek API Key",
  huggingFaceApiKeyInput: "HuggingFace API Key Input",
  addHuggingFaceApiKey: "Add HuggingFace API Key",
  mixtralApiKeyInput: "Mixtral API Key Input",
  addMixtralApiKey: "Add Mixtral API Key",
  ollamaApiKeyInput: "Ollama API Key Input",
  addOllamaApiKey: "Add Ollama API Key",
  lmStudioApiKeyInput: "LM Studio API Key Input",
  addLmStudioApiKey: "Add LM Studio API Key",
  yourApiKeys: "Your API Keys",
  noLlmApiKeysAdded: "No LLM API keys added yet.",
  setAsActive: "Set as active",
  removeApiKey: "Remove API Key",
  toggleControlPanel: "Toggle Control Panel",
  switchToLightMode: "Switch to Light Mode",
  switchToDarkMode: "Switch to Dark Mode",
  toggleCanvas: "Show/Hide Canvas",
  toggleFullscreen: "Toggle Fullscreen",
  toggleHighContrastMode: "Toggle High Contrast Mode",
  chat: "Chat",
  leaderboard: "Leaderboard",
  llmApiKeys: "LLM API Keys",
  oauthManagement: "OAuth Management",
  oauthManagementDescription: "Manage your OAuth connections and integrations",
  securityWarning: "Security Warning",
  oauthSecurityWarning: "Granting access to your accounts gives the agent full permissions. Please review and understand the implications before connecting.",
  githubIntegration: "GitHub Integration",
  githubConnectionStatus: "GitHub Connection Status",
  githubConnected: "Connected to GitHub",
  githubNotConnected: "Not connected to GitHub",
  connectGitHub: "Connect to GitHub",
  googleIntegration: "Google Integration",
  googleConnectionStatus: "Google Connection Status",
  googleConnected: "Connected to Google",
  googleNotConnected: "Not connected to Google",
  connectGoogle: "Connect to Google",
  twitterIntegration: "Twitter Integration",
  twitterConnectionStatus: "Twitter Connection Status",
  twitterConnected: "Connected to Twitter",
  twitterNotConnected: "Not connected to Twitter",
  connectTwitter: "Connect to Twitter",
  disconnect: "Disconnect",
  checkingStatus: "Checking status...",
  oauthExplanation: "OAuth connections allow the agent to access external services on your behalf. When connected, the agent can perform actions like accessing repositories, creating issues, retrieving information from integrated services, posting to social media, or accessing cloud storage.",
  browserStatus: "Browser Status",
  allowToolCreation: "Allow the agent to create new tools based on its needs.",
  allowCodeExecution: "Allow the agent to execute code directly in the environment.",
  saveCurrentSessionButton: "Save Current Session",
  sessionSaved: "Session saved!",
  sessionLoaded: "Session loaded!",
  sessionDeleted: "Session deleted!",
  sessionRenamed: "Session renamed!",
  renameSession: "Rename Session",
  newSessionName: "New session name",
  cancel: "Cancel",
  save: "Save",
  confirmDeletion: "Confirm Deletion",
  confirmDeleteSession: "Are you sure you want to delete this session? This action cannot be undone.",
  delete: "Delete",
  copiedToClipboard: "Copied to clipboard!",
  agentAvatar: "Agent Avatar",
  ai: "AI",
  copyAgentResponse: "Copy agent response to clipboard",
  agentContentWillAppearHere: "Agent content will appear here.",
  agentHtmlOutput: "Agent HTML Output",
  agentUrlOutput: "Agent URL Output",
  agentOutputCanvas: "Agent Output Canvas",
  history: "History",
};