export const fr = {
  agentReady:
    '🎯 **Agent prêt.** Veuillez entrer votre *Auth Token* pour commencer.',
  newSessionCreated: '🔄 **Nouvelle Session Créée.**',
  newSessionGenerated: 'Nouvel ID de session généré',
  sessionRetrieved: 'ID de session récupéré',
  checkingServerHealth: 'Vérification de la santé du serveur...',
  serverStatus: 'Statut du serveur',
  serverOnline: 'En ligne',
  serverOffline: 'Hors ligne',
  serverHealthCheckFailed: 'Échec de la vérification de la santé du serveur',
  tokenLoadedFromEnv: "Token chargé depuis l'environnement (AUTH_TOKEN)",
  tokenLoadedFromCookie: 'Token chargé depuis le cookie',
  tokenLoadedFromLocalStorage: 'Token chargé depuis localStorage',
  noTokenFound: 'Aucun token trouvé',
  interfaceInitialized: 'Interface initialisée (useEffect)',
  tokenSaved: 'Your authentication token has been saved.',
  newTokenSaved: 'Nouveau token sauvegardé',
  tokenRemoved: 'Your authentication token has been removed.',
  tokenDeleted: 'Token supprimé',
  historyCleared: 'The local history has been cleared.',
  debugLogCleared: 'Journal de débogage vidé.',
  sessionActive: 'Session Active',
  sessionError: 'Session Erreur',
  sessionUnknown: 'Session Inconnue',
  tokenValid: 'Token Valide',
  tokenRequired: 'Token requis',
  settings: 'Settings',
  notifications: 'Notifications',
  authToken: 'Auth Token:',
  authTokenPlaceholder: 'Collez votre Bearer Token ici',
  saveToken: 'Sauvegarder le jeton',
  agentThinking: "🤔 L'agent réfléchit...",

  tokenRequiredInput: '🔑 Veuillez sauvegarder un Bearer Token...',
  describeYourGoal: '💬 Décrivez votre objectif...',
  interrupt: 'Interrupt',
  sendMessage: 'Send Message',
  controlPanel: 'Panneau de Contrôle',
  agentStatus: "Statut de l'Agent",
  sessionId: 'Session ID',
  toolsDetected: 'Outils Détectés',
  connectionStatus: 'Statut Connexion',
  online: '✅ En ligne',
  offline: '❌ Hors ligne',
  agentCapabilities: "Capacités de l'Agent",
  sessionManagement: 'Gestion de Session',
  saveCurrentSession: 'Sauvegarder la Session Actuelle',
  noSessionsSaved: "Aucune session sauvegardée pour l'instant.",
  active: 'Active',
  toolCreation: "Création d'outils",
  codeExecution: 'Exécution de code',
  shellAccess: 'Accès Shell',
  browserAccess: 'Accès Navigateur',
  sandboxAccess: 'Accès Sandbox',
  quickActions: 'Actions Rapides',
  newSession: '🔄 Nouvelle Session',
  clearHistory: "🗑️ Vider l'Historique",
  history: 'Historique',
  debugLog: 'Journal de débogage',
  frontend: 'Frontend',
  clear: 'Vider',
  hide: 'Cacher',
  show: 'Afficher',
  toolUsed: '🛠️ Outil utilisé:',
  toolExecutedSuccessfully: 'Tool executed successfully.',
  llmConfiguration: 'Configuration LLM',
  llmProvider: 'Fournisseur LLM:',
  selectLlmProvider: 'Sélectionner un fournisseur LLM',
  llmModel: 'Modèle LLM:',
  selectLlmModel: 'Sélectionner un modèle LLM',
  llmApiKey: 'Clé API LLM:',
  llmApiKeyPlaceholder: 'Collez votre clé API LLM ici (optionnel)',
  saveLlmSettings: 'Sauvegarder les paramètres LLM',
  llmSettingsSaved: 'Paramètres LLM sauvegardés.',
  login: 'Connexion',
  email: 'Email',
  password: 'Mot de passe',
  separator: 'Séparateur',
  profile: 'Profil',
  typeYourMessage: 'Tapez votre message...',
  llmApiKeyManagement: 'Gestion des clés API LLM',
  openAiApiKeyInput: 'Entrée de la clé API OpenAI',
  addOpenAiApiKey: 'Ajouter la clé API OpenAI',
  grokApiKeyInput: 'Entrée de la clé API Grok',
  addGrokApiKey: 'Ajouter la clé API Grok',
  kimika2ApiKeyInput: 'Entrée de la clé API Kimika2',
  addKimika2ApiKey: 'Ajouter la clé API Kimika2',
  deepseekApiKeyInput: 'Entrée de la clé API Deepseek',
  addDeepseekApiKey: 'Ajouter la clé API Deepseek',
  huggingFaceApiKeyInput: 'Entrée de la clé API HuggingFace',
  addHuggingFaceApiKey: 'Ajouter la clé API HuggingFace',
  mixtralApiKeyInput: 'Entrée de la clé API Mixtral',
  addMixtralApiKey: 'Ajouter la clé API Mixtral',
  ollamaApiKeyInput: 'Entrée de la clé API Ollama',
  addOllamaApiKey: 'Ajouter la clé API Ollama',
  lmStudioApiKeyInput: 'Entrée de la clé API LM Studio',
  addLmStudioApiKey: 'Ajouter la clé API LM Studio',
  yourApiKeys: 'Vos clés API',
  noLlmApiKeysAdded: "Aucune clé API LLM ajoutée pour l'instant.",
  setAsActive: 'Définir comme actif',
  removeApiKey: 'Supprimer la clé API',
  toggleControlPanel: 'Basculer le panneau de contrôle',
  switchToLightMode: 'Passer au mode clair',
  switchToDarkMode: 'Passer au mode sombre',
  toggleCanvas: 'Afficher/Masquer le Canevas',
  toggleFullscreen: 'Basculer le mode plein écran',
  toggleHighContrastMode: 'Basculer le mode contraste élevé',
  chat: 'Chat',
  leaderboard: 'Classement',
  llmApiKeys: 'Clés API LLM',
  oauthManagement: 'Gestion OAuth',
  oauthManagementDescription: 'Gérez vos connexions et intégrations OAuth',
  securityWarning: 'Avertissement de sécurité',
  oauthSecurityWarning:
    "Accorder l'accès à vos comptes donne à l'agent toutes les permissions. Veuillez examiner et comprendre les implications avant de vous connecter.",
  githubIntegration: 'Intégration GitHub',
  githubConnectionStatus: 'Statut de la connexion GitHub',
  githubConnected: 'Connecté à GitHub',
  githubNotConnected: 'Non connecté à GitHub',
  connectGitHub: 'Se connecter à GitHub',
  googleIntegration: 'Intégration Google',
  googleConnectionStatus: 'Statut de la connexion Google',
  googleConnected: 'Connecté à Google',
  googleNotConnected: 'Non connecté à Google',
  connectGoogle: 'Se connecter à Google',
  twitterIntegration: 'Intégration Twitter',
  twitterConnectionStatus: 'Statut de la connexion Twitter',
  twitterConnected: 'Connecté à Twitter',
  twitterNotConnected: 'Non connecté à Twitter',
  connectTwitter: 'Se connecter à Twitter',
  disconnect: 'Déconnecter',
  checkingStatus: 'Vérification du statut...',
  oauthExplanation:
    "Les connexions OAuth permettent à l'agent d'accéder à des services externes en votre nom. Lorsqu'elles sont connectées, l'agent peut effectuer des actions telles que l'accès aux dépôts, la création de problèmes, la récupération d'informations depuis les services intégrés, la publication sur les réseaux sociaux ou l'accès au stockage cloud.",
  browserStatus: 'Statut du navigateur',
  allowToolCreation:
    "Permettre à l'agent de créer de nouveaux outils en fonction de ses besoins.",
  allowCodeExecution:
    "Permettre à l'agent d'exécuter du code directement dans l'environnement.",
  saveCurrentSessionButton: 'Sauvegarder la session actuelle',
  sessionSaved: 'Session sauvegardée !',
  sessionLoaded: 'Session chargée !',
  sessionDeleted: 'Session supprimée !',
  sessionRenamed: 'Session renommée !',
  renameSession: 'Renommer la session',
  newSessionName: 'Nouveau nom de session',
  cancel: 'Annuler',
  save: 'Sauvegarder',
  confirmDeletion: 'Confirmer la suppression',
  confirmDeleteSession:
    'Êtes-vous sûr de vouloir supprimer cette session ? Cette action est irréversible.',
  delete: 'Supprimer',
  copiedToClipboard: 'Copié dans le presse-papiers !',
  agentAvatar: "Avatar de l'agent",
  ai: 'IA',
  copyAgentResponse: "Copier la réponse de l'agent dans le presse-papiers",
  agentContentWillAppearHere: "Le contenu de l'agent apparaîtra ici.",
  agentHtmlOutput: "Sortie HTML de l'agent",
  agentUrlOutput: "Sortie URL de l'agent",
  agentOutputCanvas: "Canevas de sortie de l'agent",
  welcomeTitle: 'Bienvenue sur AgenticForge !',
  welcomeMessage:
    "Pour commencer, veuillez configurer votre authentification et vos clés d'API LLM.",
  setupAuthToken: "Configurer le jeton d'authentification",
  setupLLMKeys: 'Configurer les clés LLM',
  historyAndActions: 'Historique & Actions',
  loadSession: 'Charger la session',
  deleteSession: 'Supprimer la session',
  showMore: 'Voir plus',
  showLess: 'Voir moins',
  more: 'de plus',
  savedSessions: 'Sessions sauvegardées',
  sessionNamePlaceholder: 'Nom de la session',
  deleteAll: 'Tout supprimer',
  deleteAllSessions: 'Supprimer toutes les sessions',
  confirmDeleteAllSessions:
    'Êtes-vous sûr de vouloir supprimer TOUTES les {count} sessions ? Cette action est irréversible.',
  success: 'Succès',
  tokenSavedSuccess: "Jeton d'authentification enregistré avec succès !",
  authSetup: "Configuration de l'authentification",
  authSetupDescription1:
    "Pour utiliser l'agent, vous devez vous authentifier auprès de l'un des fournisseurs pris en charge ci-dessous.",
  authSetupDescription2:
    "Après la connexion, votre jeton d'authentification sera automatiquement configuré pour être utilisé avec l'agent.",
  manualTokenHint:
    'Si vous préférez utiliser un jeton manuel, vous pouvez le configurer dans la section Gestion des clés API LLM.',
  backendBearerToken: 'Jeton Bearer du backend (Info de débogage)',
  backendBearerTokenDescription:
    "Ce jeton est utilisé pour s'authentifier auprès de l'API backend.",
  debugHistory: 'Historique de débogage',
  noDebugLogs: 'Aucun journal de débogage pour le moment.',
  manualTokenSetup: 'Configuration manuelle du jeton',
  manualTokenSetupDescription:
    "Si vous préférez configurer votre jeton d'authentification manuellement :",
  manualTokenStep1: 'Allez à la page de gestion des clés API LLM',
  manualTokenStep2: 'Ajoutez votre jeton bearer dans le champ approprié',
  manualTokenStep3: 'Sauvegardez la configuration',
  goToLlmApiKeys: 'Aller à la gestion des clés API LLM',
  bearerTokenDescription1:
    "Pour utiliser l'agent, vous devez fournir un jeton d'authentification valide.",
  bearerTokenDescription2:
    "Ce jeton est utilisé pour authentifier vos requêtes auprès de l'API backend.",
};
