export const fr = {
  agentReady: "🎯 **Agent prêt.** Veuillez entrer votre *Auth Token* pour commencer.",
  newSessionCreated: "🔄 **Nouvelle Session Créée.**",
  newSessionGenerated: "Nouvel ID de session généré",
  sessionRetrieved: "ID de session récupéré",
  checkingServerHealth: "Vérification de la santé du serveur...",
  serverStatus: "Statut du serveur",
  serverOnline: "En ligne",
  serverOffline: "Hors ligne",
  serverHealthCheckFailed: "Échec de la vérification de la santé du serveur",
  tokenLoadedFromEnv: "Token chargé depuis l'environnement (VITE_AUTH_TOKEN)",
  tokenLoadedFromLocalStorage: "Token chargé depuis localStorage",
  noTokenFound: "Aucun token trouvé",
  interfaceInitialized: "Interface initialisée (useEffect)",
  tokenSaved: "Your authentication token has been saved.",
  newTokenSaved: "Nouveau token sauvegardé",
  tokenRemoved: "Your authentication token has been removed.",
  tokenDeleted: "Token supprimé",
  historyCleared: "The local history has been cleared.",
  debugLogCleared: "Journal de débogage vidé.",
  sessionActive: "Session Active",
  sessionError: "Session Erreur",
  sessionUnknown: "Session Inconnue",
  tokenValid: "Token Valide",
  tokenRequired: "Token requis",
  settings: "Settings",
  authToken: "Auth Token:",
  authTokenPlaceholder: "Collez votre Bearer Token ici",
  saveToken: "Save Token",
  agentThinking: "🤔 L'agent réfléchit...",
  
  tokenRequiredInput: "🔑 Veuillez sauvegarder un Bearer Token...",
  describeYourGoal: "💬 Décrivez votre objectif...",
  interrupt: "Interrupt",
  sendMessage: "Send Message",
  controlPanel: "Panneau de Contrôle",
  agentStatus: "Statut de l'Agent",
  sessionId: "Session ID",
  toolsDetected: "Outils Détectés",
  connectionStatus: "Statut Connexion",
  online: "✅ En ligne",
  offline: "❌ Hors ligne",
  agentCapabilities: "Capacités de l'Agent",
  toolCreation: "Création d'outils",
  codeExecution: "Exécution de code",
  shellAccess: "Accès Shell",
  browserAccess: "Accès Navigateur",
  sandboxAccess: "Accès Sandbox",
  quickActions: "Actions Rapides",
  newSession: "🔄 Nouvelle Session",
  clearHistory: "🗑️ Vider l'Historique",
  debugLog: "Journal de débogage",
  frontend: "Frontend",
  clear: "Vider",
  hide: "Cacher",
  show: "Afficher",
  toolUsed: "🛠️ Outil utilisé:",
  toolExecutedSuccessfully: "Tool executed successfully.",
};